### ISSUE TITLE
functionencoder cannot auto generate by signature string

### ISSUE THREAD

**Issue by 1500256797** [nlordell/solabi-rs#3]
I am writing code, I want to decode and encode calldata using function signature and params. I want only to pass signature string to generate functionEncoder.

```
// encoder
    const TRANSFER: FunctionEncoder<(Address, U256), (bool,)> =
        FunctionEncoder::new(selector!("transfer(address,uint256)"));
    // let TRANSFER = FunctionEncoder::new(selector!("transfer(address,uint256)"));

    let call = TRANSFER.encode_params(&(
        ethprim::address!("0x96cD66c825d57d9913BF956252df37d202464E42"),
        ethprim::uint!("14686500000000000"),
    ));
    // print the call ,call is a Vec<u8>
    println!("call: {:?}", call);
    // transfer vec<u8> to hex string
    let call_hex = hex::encode(call);
    println!("call_hex: {:?}", call_hex);

    // decode_params
    let call_vu8 = hex::decode(call_hex).unwrap();
    let transfer_decode_ret = TRANSFER.decode_params(&call_vu8).unwrap();
    println!("transfer_decode_ret: {:?}", transfer_decode_ret);

```
this code works correctly， but， if I pass the selector string in runtime, it will not work!
`let TRANSFER = FunctionEncoder::new(selector!("transfer(address,uint256)"));
`
what should I do?

**Comment by nlordell** [comment]
Weird... it should work.

From your code snippet above, I imagine that the `FunctionEncoder::new` is missing type information. You can either:

```rust
let transfer = FunctionEncoder::<(Address, U256), (bool,)>::new(selector!("transfer(address,uint256)"));
```

Or

```rust
let TRANSFER: FunctionEncoder<(Address, U256), (bool,)> =
        FunctionEncoder::new(selector!("transfer(address,uint256)"));
```

This is because the compiler can't match the `selector!(...)` function declaration to the type of the `FunctionEncoder`.

Note that there is [planned future work](https://github.com/nlordell/solabi-rs#future-work) to make this slightly nicer to use.

**Comment by nlordell** [comment]
Closing this issue for now - please feel free to re-open if the suggestions do not work.
