### ISSUE TITLE
Event Decode: Unable to Distinguish topics from data values

### ISSUE THREAD

**Issue by bh2smith** [nlordell/solabi-rs#4]
This method 

https://github.com/nlordell/solabi-rs/blob/b0253107b29f05eff450817ec0d8ca108e291b7e/src/value/encoders.rs#L170

Is combining both topics and data values returning the same `Vec<Value>` 

So that the following two Event Logs described in https://github.com/Mintbase/arak/issues/19 different because of the length of the topics array) get decoded in a way that makes them look similar

Would it make sense to return a tuple here `(Vec<Value>, Vec<Value>)` for `topics_fields` and `data_fields`? If so, I would be happy to implement it.

**Comment by nlordell** [comment]
Thanks for the investigation!

From the Solidity docs:

> `topics[0]`: `keccak(EVENT_NAME+"("+EVENT_ARGS.map(canonical_type_of).join(",")+")")` (`canonical_type_of` is a function that simply returns the canonical type of a given argument, e.g. for `uint indexed foo`, it would return `uint256`).

This means that, indeed, `indexed` fields in events are treated the same WRT the `topic[0]` value as non-indexed events.

I think your proposal makes sense (that is to treat topic and data values differently when decoding).

This will break `arak` for sure though (which assumed that `indexed` played a role in the `topic[0]` value), in which case your suggestion in the linked PR makes sense as well.

**Comment by bh2smith** [comment]
I also made a reasonable fix to arak that is good enough for my purposes without making any changes here

https://github.com/Mintbase/arak/pull/20

**Comment by nlordell** [comment]
I think that an `arak` change is needed in any case (just because you can't distinguish from event signature alone how to decode it 😞). This is a pretty strong argument to disallow `contract = "*"` configurations in general in `arak`, since there is no guarantee that the event can be decoded anyway.

Will try and propose a fix to this to `solabi` crate this week.
